### ISSUE TITLE
[bug report] Unable to open any of the article links on the xlog.app page

### ISSUE THREAD

**Issue by cjh0613** [Crossbell-Box/xLog#790] opened 2023-07-18 00:50 UTC
Unable to open any of the article links on the https://xlog.app page:

`Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1220422868`

**Comment by DIYgod** [comment] 2023-07-18 00:55
I cannot reproduce it, but I suspect the issue may be related to CDN or some strange cache in your region.

**Comment by DIYgod** [comment] 2023-07-18 01:09
I discovered a dependency bug, it has been fixed in 8c382bdbe38d60cd377f7e2a298f7cd53045671e. It is currently being released.

**Closed as completed** 2023-07-19 08:21 UTC
